Check for existing FB connection before making a new one.
concord-consortium/activity-player pull request #228
Opened 2021-04-05 17:58 UTC by knowuh

This change checks if the application already has an initialized DB connection before making a new one.

Mostly this just silences a error message in the console.

Story: https://www.pivotaltracker.com/story/show/177479032

2021-04-05 18:20 UTC, scytacki approved these changes
Seems OK to me.

2021-04-05 18:27 UTC, dougmartin approved these changes
Looks good :+1:

2021-04-06 20:35 UTC, scytacki requested changes
remove some redundant code.

2021-04-06 20:35 UTC, scytacki commented on src/components/activity-completion/report-backup-options.tsx
> +      : <>Report My Work</>;
Could remove this.

2021-04-07 00:14 UTC, scytacki approved these changes
Looks good.

2021-04-07 00:15 UTC, merged