Add page linking using page id [#176197155]
concord-consortium/activity-player pull request #97
Opened 2020-12-28 18:40 UTC by dougmartin

2020-12-28 19:01 UTC, mklewandowski commented on src/utilities/activity-utils.ts
> +  return parseInt(pageQueryValue, 10) || 0;
This is probably a good place to check if the page number specified in the URL param is also less than 0 or greater than `activity.pages.length`.  We should probably return 0 in those cases as well.

2020-12-28 19:04 UTC, mklewandowski approved these changes
👍 Looks good.  If it's not too much trouble, I would add a line about how to use the page id in the URL param section of the readme and check if the page number is less than 0 or greater than the number of activity pages in `getPagePositionFromQueryValue `.

2020-12-28 20:18 UTC, dougmartin commented
@mklewandowski I've added range check on the page parameter: https://github.com/concord-consortium/activity-player/pull/97/commits/4c992a9bd09b48df0e9e76a40b0e7efaa96009bf

2020-12-28 20:24 UTC, dougmartin commented
@mklewandowski I also updated the readme and fixed a lint error introduced in my earlier commit.

2020-12-28 20:33 UTC, scytacki requested changes
Seems good to me. It is nice to support both a page index and a page id.

Can you document better what `page_[id]` maps to in the activity export file. Is the id in the file `page_123` or is the id in the file `123`?  

Some of these files are manually created instead just being exported from LARA so it is useful to document this.
Since the way the ids in the exported

2020-12-29 14:18 UTC, dougmartin commented
@scytacki is this a better description of the page id parameter? https://github.com/concord-consortium/activity-player/pull/97/commits/e7e083dc88e55a44f8628c0ed83b81c414c2663c

2021-01-19 19:14 UTC, dougmartin commented
@scytacki I fixed a build error with a new json file that was added - is this good to merge?

2021-01-22 01:55 UTC, scytacki approved these changes
This is good. Sorry I didn't see this sooner.

Next time if you 're-request' a review I'll see it sooner. That is the little recycle icon next to the reviewer names.

2021-01-22 01:55 UTC, merged